/* Generated By:JavaCC: Do not edit this line. justConstants.java */
package ParserPackage;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface justConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 5;
  /** RegularExpression Id. */
  int TYPE = 6;
  /** RegularExpression Id. */
  int LGESCHWEIFT = 7;
  /** RegularExpression Id. */
  int RGESCHWEIFT = 8;
  /** RegularExpression Id. */
  int ELKLAMMER = 9;
  /** RegularExpression Id. */
  int ERKLAMMER = 10;
  /** RegularExpression Id. */
  int SEMI = 11;
  /** RegularExpression Id. */
  int EQUALS = 12;
  /** RegularExpression Id. */
  int RRKLAMMER = 13;
  /** RegularExpression Id. */
  int RLKLAMMER = 14;
  /** RegularExpression Id. */
  int KOMMA = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int RETURN = 17;
  /** RegularExpression Id. */
  int KAUFUND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int GLEICHGLEICH = 20;
  /** RegularExpression Id. */
  int AUSGLEICH = 21;
  /** RegularExpression Id. */
  int KLEINER = 22;
  /** RegularExpression Id. */
  int KLEINERGLEICH = 23;
  /** RegularExpression Id. */
  int GROESSER = 24;
  /** RegularExpression Id. */
  int GROESSERGLEICH = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int MAL = 28;
  /** RegularExpression Id. */
  int DIV = 29;
  /** RegularExpression Id. */
  int AUSRUF = 30;
  /** RegularExpression Id. */
  int BYREF = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int WORD = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int IDENT = 36;
  /** RegularExpression Id. */
  int STAT = 37;
  /** RegularExpression Id. */
  int konkSTAT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"program\"",
    "<TYPE>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\")\"",
    "\"(\"",
    "\",\"",
    "\"while\"",
    "\"return\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"< \"",
    "\" <=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\"byref\"",
    "<NUMBER>",
    "<DIGIT>",
    "<WORD>",
    "<LETTER>",
    "<IDENT>",
    "<STAT>",
    "<konkSTAT>",
    "\";;\"",
  };

}
