/* Generated By:JavaCC: Do not edit this line. justConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface justConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 5;
  /** RegularExpression Id. */
  int LGESCHWEIFT = 6;
  /** RegularExpression Id. */
  int RGESCHWEIFT = 7;
  /** RegularExpression Id. */
  int ELKLAMMER = 8;
  /** RegularExpression Id. */
  int ERKLAMMER = 9;
  /** RegularExpression Id. */
  int TYPE = 10;
  /** RegularExpression Id. */
  int SEMI = 11;
  /** RegularExpression Id. */
  int EQUALS = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int WORD = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int IDENT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"program\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<TYPE>",
    "\";\"",
    "\"=\"",
    "<NUMBER>",
    "<DIGIT>",
    "<WORD>",
    "<LETTER>",
    "<IDENT>",
    "\";;\"",
  };

}
